baseURL = 'https://example.com'
languageCode = 'en-GB'
title = 'Your Name'
theme = 'nkmason-like'

[params]
  author = 'Your Name'
  description = 'Description of your site'
  homeTitle = 'Hello (●＾o＾●)'
  showRecentPosts = true
  recentPostsCount = 5

[[params.social]]
  name = 'GitHub'
  url = 'https://github.com/yourusername'

[[params.social]]
  name = 'LinkedIn'
  url = 'https://linkedin.com/in/yourusername'

[[params.social]]
  name = 'Email'
  url = 'mailto:your@email.com'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 10
  
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 20
  
  [[menu.main]]
    name = 'Blog'
    url = '/posts/'
    weight = 30

[outputs]
  home = ['HTML', 'RSS']
  page = ['HTML', 'RSS']
  section = ['HTML', 'RSS']

[outputFormats]
  [outputFormats.RSS]
    mediatype = 'application/rss+xml'
    baseName = 'rss'
